In [6]:
import pandas as pd
import numpy as np

from google_play_scraper import reviews, Sort

In [7]:
cbe_app_id = "com.combanketh.mobilebanking"
boa_app_id = "com.boa.boaMobileBanking"
dashen_app_id = "com.dashen.dashensuperapp"

In [22]:
def scrape_reviews(app_id, bank_name, count=800):
    
    result, continuation_token = reviews(
        app_id,
        lang='en',
        country='et',
        sort=Sort.NEWEST,
        count=count
    )
    
    df = pd.DataFrame(result)
    
    df['bank'] = bank_name
    
    return df

In [23]:
cbe_reviews = scrape_reviews(cbe_app_id, "CBE")
boa_reviews = scrape_reviews(boa_app_id, "BOA")
dashen_reviews = scrape_reviews(dashen_app_id, "Dashen")

# Commercial Bank of Ethiopia Reviews

In [24]:
cbe_reviews.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
0,eb3cc438-1c10-4e72-8851-3efff6a04135,Hamza Jemal,https://play-lh.googleusercontent.com/a/ACg8oc...,this app very full,5,0,5.3.0,2026-05-16 09:17:00,None,None,5.3.0,CBE
1,f8209985-ea16-4f28-bb48-d6a7276f0f08,Ras Abale,https://play-lh.googleusercontent.com/a-/ALV-U...,good apps,4,0,5.3.0,2026-05-16 07:18:33,None,None,5.3.0,CBE
2,a983bc98-7ea7-4ac6-8fed-039ed2a7de0a,Teyhb,https://play-lh.googleusercontent.com/a/ACg8oc...,ok,5,0,5.3.0,2026-05-16 03:43:47,None,None,5.3.0,CBE
3,f0f249ac-ba95-4ad8-ad1d-c435693b7bf9,Abrha Hadgu,https://play-lh.googleusercontent.com/a-/ALV-U...,this update got crazy i don't know what's goin...,1,0,NaN,2026-05-15 23:20:32,None,None,NaN,CBE
4,31cf1f70-1cd8-427c-9cd5-1ccb4113facf,Ademasu Shadaga,https://play-lh.googleusercontent.com/a/ACg8oc...,thanks for you 😘,5,0,NaN,2026-05-15 20:11:22,None,None,NaN,CBE

In [25]:
cbe_reviews = cbe_reviews[
    [
        'reviewId',
        'userName',
        'content',
        'score',
        'thumbsUpCount',
        'at',
        'bank'
    ]
]

In [26]:
cbe_reviews.columns = [
    'review_id',
    'user_name',
    'review',
    'rating',
    'thumbs_up',
    'review_date',
    'bank'
]

In [61]:
cbe_reviews.isnull().sum()

review_id       0
user_name       0
review          0
rating          0
thumbs_up       0
review_date     0
bank            0
clean_review    0
dtype: int64

In [62]:
cbe_reviews.dropna(subset=['review'], inplace=True)

In [27]:
cbe_reviews.dropna(subset=['review'], inplace=True)

In [28]:
cbe_reviews.drop_duplicates(subset=['review'], inplace=True)

In [29]:
import re

def clean_text(text):
    
    text = text.lower()
    
    text = re.sub(r"http\\S+", "", text)
    
    text = re.sub(r"[^a-zA-Z\\s]", "", text)
    
    text = re.sub(r"\\s+", " ", text).strip()
    
    return text

In [30]:
cbe_reviews['clean_review'] = cbe_reviews['review'].apply(clean_text)

In [31]:
cbe_reviews.to_csv(
    "../data/processed/cbe_reviews_clean.csv",
    index=False
)

In [32]:
len(cbe_reviews)

607

In [33]:
cbe_reviews.shape

(607, 8)

# Bank of Abyssinia Reviews

In [34]:
boa_reviews.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
0,5f69466d-ec06-4eb5-816c-296accffeff2,Wende Rege,https://play-lh.googleusercontent.com/a-/ALV-U...,was Good 🙏,5,0,26.05.11,2026-05-16 00:10:06,None,None,26.05.11,BOA
1,f9246b8a-6688-4249-b804-0b0c5dd60590,hamza Bedr,https://play-lh.googleusercontent.com/a/ACg8oc...,cool,5,0,25.09.03,2026-05-15 21:07:21,None,None,25.09.03,BOA
2,21bcff26-5b05-485d-958f-4832ec1fac01,Tsegay Teklay,https://play-lh.googleusercontent.com/a/ACg8oc...,Its Good,5,0,25.09.03,2026-05-15 15:01:09,None,None,25.09.03,BOA
3,c5eb7589-59b7-4d72-8aa9-100a703ecaa3,shambel mulugeta,https://play-lh.googleusercontent.com/a-/ALV-U...,good,5,0,26.03.13,2026-05-14 21:18:44,None,None,26.03.13,BOA
4,c3bb042c-844b-4580-98b9-df418622b2fb,Hamid Abdella,https://play-lh.googleusercontent.com/a/ACg8oc...,it's very good app,5,0,NaN,2026-05-12 11:50:32,None,None,NaN,BOA

In [35]:
boa_reviews = boa_reviews[
    [
        'reviewId',
        'userName',
        'content',
        'score',
        'thumbsUpCount',
        'at',
        'bank'
    ]
]

In [36]:
boa_reviews.columns = [
    'review_id',
    'user_name',
    'review',
    'rating',
    'thumbs_up',
    'review_date',
    'bank'
]

In [63]:
boa_reviews.isnull().sum()

review_id       0
user_name       0
review          0
rating          0
thumbs_up       0
review_date     0
bank            0
clean_review    0
dtype: int64

In [64]:
boa_reviews.dropna(subset=['review'], inplace=True)

In [38]:
boa_reviews.drop_duplicates(subset=['review'], inplace=True)

In [39]:
import re

def clean_text(text):
    
    text = text.lower()
    
    text = re.sub(r"http\\S+", "", text)
    
    text = re.sub(r"[^a-zA-Z\\s]", "", text)
    
    text = re.sub(r"\\s+", " ", text).strip()
    
    return text

In [40]:
boa_reviews['clean_review'] = boa_reviews['review'].apply(clean_text)

In [41]:
cbe_reviews.to_csv(
    "../data/processed/boa_reviews_clean.csv",
    index=False
)

In [65]:
boa_reviews.shape

(663, 8)

# Dashen Bank Reviews

In [44]:
dashen_reviews.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
0,12ebd51a-7912-464b-a81b-14a0aac358da,Jaalataa Gazaali,https://play-lh.googleusercontent.com/a-/ALV-U...,ok,5,0,1.9.04,2026-05-15 20:41:19,NaN,NaT,1.9.04,Dashen
1,68dd84a3-07ab-41d9-aff8-ad7916ff71a8,Hayredin Redwan,https://play-lh.googleusercontent.com/a-/ALV-U...,best app so far. thank you,5,0,1.9.09,2026-05-15 18:33:32,NaN,NaT,1.9.09,Dashen
2,78284116-8313-4ca8-a28c-61ce4fa44ee6,king mele,https://play-lh.googleusercontent.com/a/ACg8oc...,Very Annoying App i tried to open virtual bank...,1,0,1.9.14,2026-05-14 19:33:42,NaN,NaT,1.9.14,Dashen
3,b4a7ea95-727b-4501-8d84-77db88187c84,Ahmed Abdi,https://play-lh.googleusercontent.com/a/ACg8oc...,good,5,0,1.9.14,2026-05-14 19:26:20,NaN,NaT,1.9.14,Dashen
4,59a20f9e-bb87-4d5f-bee7-ce19f19baddf,Bellixs,https://play-lh.googleusercontent.com/a-/ALV-U...,good,5,0,1.8.1,2026-05-14 17:35:20,NaN,NaT,1.8.1,Dashen

In [45]:
dashen_reviews.shape

(800, 12)

In [46]:
dashen_reviews = dashen_reviews[
    [
        'reviewId',
        'userName',
        'content',
        'score',
        'thumbsUpCount',
        'at',
        'bank'
    ]
]

In [47]:
dashen_reviews.shape

(800, 7)

In [48]:
dashen_reviews.columns = [
    'review_id',
    'user_name',
    'review',
    'rating',
    'thumbs_up',
    'review_date',
    'bank'
]

In [49]:
dashen_reviews.dropna(subset=['review'], inplace=True)

In [50]:
dashen_reviews.shape

(800, 7)

In [66]:
dashen_reviews.isnull().sum()

review_id       0
user_name       0
review          0
rating          0
thumbs_up       0
review_date     0
bank            0
clean_review    0
dtype: int64

In [67]:
dashen_reviews.drop_duplicates(subset=['review'], inplace=True)

In [52]:
dashen_reviews.shape

(671, 7)

In [53]:
import re

def clean_text(text):
    
    text = text.lower()
    
    text = re.sub(r"http\\S+", "", text)
    
    text = re.sub(r"[^a-zA-Z\\s]", "", text)
    
    text = re.sub(r"\\s+", " ", text).strip()
    
    return text

In [54]:
dashen_reviews['clean_review'] = dashen_reviews['review'].apply(clean_text)

In [55]:
dashen_reviews.to_csv(
    "../data/processed/dashen_reviews_clean.csv",
    index=False
)

In [68]:
dashen_reviews.shape

(671, 8)

# Combined Dataset

In [56]:
all_reviews = pd.concat(
    [cbe_reviews, boa_reviews, dashen_reviews],
    ignore_index=True
)

In [58]:
all_reviews.to_csv(
    "../data/processed/all_bank_reviews.csv",
    index=False
)

In [69]:
all_reviews.shape

(1941, 8)

In [70]:
print(len(cbe_reviews))
print(len(boa_reviews))
print(len(dashen_reviews))

607
663
671